### ISSUE TITLE
Rhinoesc and version 1.94

### ISSUE THREAD

**Issue by kaczork** [AlkaMotors/AM32-MultiRotor-ESC-firmware#105]
Hi! When flashing Rhinoesc 80A with version 1.94 (AM32_RHINO80A_F051_1.94.hex) it just produces constant beeps when started and just does not work at all. Flashing was done by Multi ESC Config Tool 1.82. I've tried so far:
1. setting default values in tool,
2. trying to calibrate throttle range (this is not possible at all).

Everyting seems to work when flashing back to 1.93. Am I doing something wrong?

**Comment by AlkaMotors** [comment]
I'll check it out. Are you using a servo input?

**Comment by kaczork** [comment]
I'm using a FlySky FS-BS6 receiver as input to drive ESC (if this is what you meant)...

**Comment by AlkaMotors** [comment]
OK, i can cofirm the servo input was not working on 1.94. version 1.95 should fix this. 
https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/releases/tag/v1.95

**Comment by kaczork** [comment]
Hi! Thank you for quick response! Hereby I confirm 1.95 fixes the startup issue. I don't know how it works in general, as I have just torn down my model, but it boots properly, seems the sinusoidal startup is there :)
