### ISSUE TITLE
Feature request: eprom define the names and parameters for the configurator 

### ISSUE THREAD

**Issue by Voodoobrew101** [AlkaMotors/AM32-MultiRotor-ESC-firmware#18]
Because the crawler and quad parameters are drasticaly different. This way you donvt need to update the configurator as often also. Then configure the eprom with some #define yada ya, so it contains the name of the value, the possible values, the default and/or current value, and what type of input box (type or slider). 
Just an idea not sure if the eprom has room for it.

**Comment by AlkaMotors** [comment]
We do have a lot of space for EEprom settings. The configurator will still have to know something about the data it is receiving to brake it down into its parts but I think a separate space for crawlers might be a good plan. We are currently using 48 of 1024 Bytes in flash space for settings. Its not a bad idea to have the eeprom define the settings parameters but it does make the size of the data transfer much larger each time.

**Comment by Voodoobrew101** [comment]
In order upload decently descriptive names for the sliders It does seem like it would be rather wasteful.
![image](https://user-images.githubusercontent.com/28468053/126516647-0454be12-d7af-40a9-9f1c-6ac87e669e4c.png)
