### ISSUE TITLE
[Feature Request] louder beeper

### ISSUE THREAD

**Issue by JyeSmith** [AlkaMotors/AM32-MultiRotor-ESC-firmware#33]
Any chance of making the beeper louder?  I use it as my only way of finding the quad, or quickly confirming an rc link after plugging in.

**Comment by Voodoobrew101** [comment]
You can make it louder in sounds.h or is it sounds.C, if you are compiling it. I dont know how loud it can go. There is a warning it can ruin things, i never tested it out. Its just not available to change in the configurator.
