### ISSUE TITLE
T-motor F55A ESC flash help

### ISSUE THREAD

**Issue by sedlacekdavid** [AlkaMotors/AM32-MultiRotor-ESC-firmware#36]
Hi, any ideas how to flash AM32 bootloader? I'd like to test this interesting project. Thanks David.

**Comment by Voodoobrew101** [comment]
Find your esc in the compatability list: https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/wiki/List-of-Supported-Hardware
Video: https://youtu.be/KIPSlTjpdak
Written: https://docs.google.com/document/d/1iIpkrYYRz7Iy7lsO5JanFqNRh-Jft2vySzSegLf8F9c/edit?usp=drivesdk
