### ISSUE TITLE
Add GD32f3 targets like AIRBOT 45a

### ISSUE THREAD

**Issue by ss8688** [AlkaMotors/AM32-MultiRotor-ESC-firmware#39]
please add GD32f3 support

**Comment by AlkaMotors** [comment]
Airbot has not sent over any schematics for their ESC's. I have asked for schematucs and pinouts. They sent a few blank ESC's expecting me to maybe beep out the traces? . I am not going to do this or donate my time to them so unless they want to provide information and money there will be no airbot support. I recommend supporting companies like Diatone or T-motor instead.
