### ISSUE TITLE
Where can I get the pins map and pins def?

### ISSUE THREAD

**Issue by gcrisis** [AlkaMotors/AM32-MultiRotor-ESC-firmware#40]
Do you have a full pin function description?
Or have to get the info from source code ?

**Comment by AlkaMotors** [comment]
This is where the pins for the the different targets are defined. https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/blob/master/Inc/targets.h

**Comment by gcrisis** [comment]
Thank You！
