### ISSUE TITLE
Info on brushed mode setup?

### ISSUE THREAD

**Issue by howels** [AlkaMotors/AM32-MultiRotor-ESC-firmware#71]
I've seen references to brushed mode, if this is supported could we please get a short page explaining how it works and which ESC connections to use.

**Comment by Voodoobrew101** [comment]
https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/blob/264b85bf20b692f1352e9bac3eed66dee3a2b2d9/Src/main.c#L186-L190

Set BRUSHED_MODE = 1; 
then uncomment your target in targets.h
Then in github actions -  Build AM32 F051 Firmware
