### ISSUE TITLE
 ST-LINK error (DEV_TARGET_CMD_ERR)

### ISSUE THREAD

**Issue by slider409** [AlkaMotors/AM32-MultiRotor-ESC-firmware#75]
I keep receiving this error when I try and connect to an Aikon AK32 35A ESC. I am using the latest firmware on the ST-link V2, and the newest STM32CubeProgrammer. I have tried all the options available in the st link options and nothing changes. I have googled the error and can't seam to find anything related to what we are doing here. I am very new to this and any help would be greatly appreciated.

**Comment by AlkaMotors** [comment]
Well, we don't make Aikon Esc's nor St-Links , nor the stm32CubeProgrammer. Join the slack and we can help you out if you still haven't been able to connect but none of those things are anything we can control. St micros forums maybe a better place to start.
