### ISSUE TITLE
bl esc on slot car

### ISSUE THREAD

**Issue by mtaddei** [AlkaMotors/AM32-MultiRotor-ESC-firmware#76]
Gd day from Italy,
we are a group of slot car modeller that are trying to fit brushless motor on slot car.
We'll like to know if it is possible turn off the radio pwm signal setting it always at max speed
enabling us to controll the motor speed directly with the voltage supplied by our slot controller
on the track braid

Tnks for your kind replay

Max

**Comment by AlkaMotors** [comment]
Yes, there is a mode made just for this purpose. You just need to compile the firmware with those options enabled. If you have a specific esc in mind i can attach one here.

**Comment by mtaddei** [comment]
the esc is FEICHAO 40 AMP

**Comment by mtaddei** [comment]
just removed the wrapping and the processor is an ATMEGA8AU, is compatible or not?

**Comment by AlkaMotors** [comment]
No, 8 bit mcu's are not supported. It must be a 32 bit arm mcu.

**Comment by AlkaMotors** [comment]
No 8 bit mcu support.
