### ISSUE TITLE
pwm control

### ISSUE THREAD

**Issue by aa651685** [AlkaMotors/AM32-MultiRotor-ESC-firmware#77]
When I use pwm control, the motor can make a beeping sound, but when the pwm is in the 1051-2001 range, the motor does not work and the sound disappears.

**Comment by AlkaMotors** [comment]
Are you driving a motor one way? or two direction? If you give it a signal outside the normal servo range it will keep on beeping. You must give it an appropriate signal to arm the esc after the first power up beeps. This must be one second of signal between 1450 and 1550 by default for two direction or below 1050us for single direction. after arming, then the motor will respon to a valid servo signal between 900 and 2100 ( depending on the set end points) .
