### ISSUE TITLE
does am32 support flycolor_raptor 50a ?

### ISSUE THREAD

**Issue by IFG-InFinityGamer** [AlkaMotors/AM32-MultiRotor-ESC-firmware#88]
flycolor_raptor 50a ues STM32G071 MCU,can i use the [AM32_G071_64K_1.88.hex](https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/releases/download/v1.88/AM32_G071_64K_1.88.hex) or use [AM32_FLYCOLOR_1.88.hex](https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/releases/download/v1.88/AM32_FLYCOLOR_1.88.hex) also be ok ?
thanks

**Comment by AlkaMotors** [comment]
not sure, I have never had that one to try. Chances are the g071 will work. Since I am a month late responding to this maybe you have the answer? Come join the slack for faster support.
