### ISSUE TITLE
Feature Request: Linux Configurator

### ISSUE THREAD

**Issue by stronnag** [AlkaMotors/AM32-MultiRotor-ESC-firmware#9]
Please might we have a Linux configurator (or a source release so it can be ported).

**Comment by AlkaMotors** [comment]
Hey stronnag, I have a linux version already but I have a couple of finishing touches to do. This weekend I will get it uploaded into the release folder. Source will be up soon too. There is also work being done to add compatibility with blheli_configurator that will be coming in the future.

**Comment by stronnag** [comment]
Thanks. Look forward to being able to test it.

**Comment by AlkaMotors** [comment]
Check it out and see if it works for you.
https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/tree/master/Release/CONFIG%20TOOL

**Comment by stronnag** [comment]
Tested (Arch Linux). No problems. 
Thanks. Look forward to be able to build it so it can use local preferences (like qt5ct).
