### ISSUE TITLE
[Feature Request] frsky f.port support

### ISSUE THREAD

**Issue by hedlesschkn** [AlkaMotors/AM32-MultiRotor-ESC-firmware#95]
It has been discussed here and in the blheli_32 channels that the new F4 based escs have their "telem" pad tied to a pin on the mcu that is not bidirectional.  Frsky s.port telemetry is a bidirectional protocol so while enabling s.port on the older style _32 escs was a cool feature, it's physically not possible on the F4 hardware.

Given that the PWM pin can still speak bidirectional d-shot I'm assuming that pad must be on a hardware pin that supports bidirectional communication.  Is there any chance we could implement frsky f.port (their newer faster protocol that's basically sbus and s.port combined onto a single wire) on the PWM pin?  This would bring back the direct to frsky telemetry feature for airplane and combat robotics folks on the new F4 escs.  I'd be happy to help develop this but wanted someone more AM32 and hardware knowledgeable to give it the gut check in case I'm missing something obvious here?

**Comment by AlkaMotors** [comment]
I am not sure why the pin cannot support bidirectional telemetry on the f4? Has this been confirmed with blheli32 team?. I have not tried to receive with that pin f4.. only transmit,  but the pin PB6 can be configured as half duplex serial for transmit or receive. I will do a quick test tomorrow. Do you know where I can find the info on the sport spec? I think we can spare a few more bytes for s.port.
