### ISSUE TITLE
Does the AM32 ESC support (bi-direction) Dshot600 now?

### ISSUE THREAD

**Issue by GuoDaShan** [AlkaMotors/AM32-MultiRotor-ESC-firmware#96]
I saw in WIKI that it only supports (bi-direction Dshot300)，but it is described on the home page that（bi-direction）Dshot600 can be supported。
So, do AM32 electronic governors support （bi-direction）Dshot600 now?

I think the update time of WIKI is October 2021. Maybe it should be updated~
----------------------------------------
中文或许能更好的描述我这个问题，在首页中我看到AM32支持Dshot300 Dshot600 PWM，但是在WIKI 中介绍说是使用双向Dshot仅仅支持Dshot300，因为使用双向Dshot600 会不可避免的出现错误。
WIKI是2021年10月更新的，首页更新时间是2022年11月，所以想问下现在得AM32固件支持（双向）Dshot600了吗？

**Comment by AlkaMotors** [comment]
dshot 600 has no advantage over 300 and is more prone to seeing some dshot error when you get over 500,000 erpm. That's is the reason for the 300 reccomendation.
