### ISSUE TITLE
Linux build instructions

### ISSUE THREAD

**Issue by JoshMcguigan** [AlkaMotors/AM32-MultiRotor-ESC-firmware#97]
Hi, and thanks for sharing this project!

I notice you have build instructions for windows - do you plan to document building on linux? 

I was able to build on arch linux by installing `arm-none-eabi-gcc`/`arm-non-eabi-newlib` and deleting the line in `tools.mk` that checks the gcc version (because my version was newer than the specified version). From there you can run `make $TARGET` where `$TARGET` comes from `target.h` (the makefile defines whichever target you pass to make). The build output will be in the `obj` directory.

**Comment by AlkaMotors** [comment]
For linux just use "make".. If you do not have the proper gcc version it will give a warning and it also prompt the user to type 'make arm-sdk-install'. It will then install the proper version GCC for you. I do not reccomend using the latest.
