### ISSUE TITLE
skystars am32 55a esc no longer controls speed 

### ISSUE THREAD

**Issue by beigevanman** [AlkaMotors/AM32-MultiRotor-ESC-firmware#99]
updated from1.88 to 1.91  to fix multi tne startup issue

all esc flash said successful

now no response from esc ..no startup tones   configurator does still see esc just cant read

**Comment by AlkaMotors** [comment]
Make sure you flashed the target that say e230 or 'Skystars butter'. There were two different microcontrollers used for the km55 .The 'Skystars km55' target will.be for the f051. Use this one for the red heatsink version https://github.com/AlkaMotors/AM32-MultiRotor-ESC-firmware/releases/download/v1.92/AM32_SKYSTARS_BUTTER_E230_1.92.hex

**Comment by beigevanman** [comment]
Hi..thanks for the quick response...how do I reflash it with this as its
seem but not responding


I just bought tye St link v2

Can it be done through the comfigurator ??

**Comment by beigevanman** [comment]
Tried the 1.92 on another matching esc and it stopped working

was able to flash it back to 1.88 with AM32_GD32E230_SKYSTARS_KM55_1_88.hex

and they work again

it is a red 20x20 long 55a esc

**Comment by AlkaMotors** [comment]
It sounds like you are using the online config tool? 
Do not use the online esc configurator. This is no longer supported . It will not work for version 1.92 an newer. They made some changes in december that require every single new firmware name to be entered into the config tool in order to use, so new versions definitely will not work. Please use the official am32 config tool that's in the readme.

**Comment by beigevanman** [comment]
I used the program  version was 1.87 I think

**Comment by AlkaMotors** [comment]
I just tested version 1.92. The file i linked above. "SKYSTARS BUTTER E230" on the red km55 and it runs normally. This file had been flashed to quite a few of them so far. The only thing that would make it not work after flashing is if the file were wrong, can you do a screen capture of video of the flashing?

**Comment by beigevanman** [comment]
When it trys to connect it say BAD or no ACK from IF

**Comment by beigevanman** [comment]
![20230205_210037](https://user-images.githubusercontent.com/107796252/216846528-1d5dad44-c8da-4a7f-929b-86a614f375bc.jpg)

**Comment by AlkaMotors** [comment]
How did you revert the last one from 1.92 back to 1.88 ?

**Comment by AlkaMotors** [comment]
Can you join either the discord or slack channel and we can help you a bit faster with the problem. What size are the firmware files you download? They should be about 70kb hex files. If you right click the file and save target as it might not download correctly.

**Comment by beigevanman** [comment]
The second one I used the file you suggested that said success but wouldn't
spin the motors

I was just lucky I guess being able to.downgrade

The  first one I did is in the pic and won't do.anything

I'm.hoping the v2 adapter and cube programmer sorts it

I

**Comment by beigevanman** [comment]
I've used 3 different ones now to see if that made any difference.   1st
was a f7.mini skystars ...then a f4 speedybee then a blue one powerhobby or
something Ilike that...they all.work.on the working one and all.the same on
the not working one

**Comment by AlkaMotors** [comment]
Use this method to revert the firmware. Did you check the file size? I flashed 1.92 to the ESC with f7 and f4. 

https://youtu.be/XE7uxUA_RqY

**Comment by beigevanman** [comment]
All.the leads.were made up correctly for each combo  ..they all.work.in
betaflight .no issues...just  the bad ack and no output.

Are you in the US??

**Comment by beigevanman** [comment]
I don't get the flashing screen options at all.just the m1 and that's it

**Comment by AlkaMotors** [comment]
I am in Canada

**Comment by beigevanman** [comment]
It Verked. .. had to power cycle it about 30 times then had the Good ack
message and flashing option popped up.

I used the e230 butter 1.88 .. put it back to how it was.

Omly wanted to update so the post tones were in sync

Thank.you for.your time

It seems the am32 is very stable and very smooth with power delivery
...motors even sound happier

Again thank you

**Comment by AlkaMotors** [comment]
I glad it's working but it's really strange that 1.92 is not working. Those versions have been out for a while. Watch out about the file size if you download the hex file from the internet with a right click and 'save as'. It can produce a file with the right name but not the correct data. Hopefully we will make flashing a little easier in the future and we can pull right from the GitHub repo into the flashing tool.

**Comment by beigevanman** [comment]
The front end is a little old school ,win98. But it works.

With a little.bit of youth related app tap tap.mouse .

Could be very easily resolved .

With Chris rosser recently.singing the am32 praises on his channel and
Bardwell worshiping the ground he walks on...hopefully will be the new
sliced bread in the fpv community
